tibble::tribble(
                           ~track,                      ~room,              ~room_name, ~capacity,
                        "plenary",           "0. Potomac A+B",           "Potomac A+B",      2176,
                              "A",             "1. Potomac C",             "Potomac C",       540,
                              "B",             "2. Potomac D",             "Potomac D",       540,
                              "C",        "3. Cherry Blossom",        "Cherry Blossom",       720,
                              "D", "4. National Harbor 10+11", "National Harbor 10+11",       490,
                               NA,              "5. Maryland",              "Maryland",      1500,
                               NA,    "6. Riverview Ballroom",    "Riverview Ballroom",        NA,
                               NA,       "7. Orchard Terrace",       "Orchard Terrace",        NA,
                "shiny-prod-apps",                         NA,     "National Harbor 2",        NA,
        "causal-inference-rstats",                         NA,     "National Harbor 3",        NA,
         "ggplot2-graphic-design",                         NA,   "National Harbor 4+5",        NA,
              "get-started-shiny",                         NA,   "National Harbor 6+7",        NA,
                  "tidymodels-ml", "4. National Harbor 10+11", "National Harbor 10+11",        NA,
                  "rmd-to-quarto",                         NA, "National Harbor 12+13",        NA,
                  "art-from-code",                         NA,            "Maryland 1",        NA,
             "get-started-quarto",                         NA,            "Maryland 2",        NA,
                       "teach-ds",                         NA,            "Maryland 3",        NA,
             "intro-to-tidyverse",                         NA,          "Maryland 4+5",        NA,
               "ds-for-sysadmins",                         NA,            "Maryland 6",        NA,
        "clinical-reporting-in-r",                         NA,          "Chesapeake D",        NA,
        "people-analytics-rstats",                         NA,          "Chesapeake E",        NA,
               "build-tidy-tools",                         NA,          "Chesapeake F",        NA,
                     "wtf-rstats",                         NA,      "Chesapeake 4+5+6",        NA,
            "pkg-dev-masterclass",                         NA,      "Chesapeake G+H+I",        NA
  )
